name: Build Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.18.0' ]

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        go get -u github.com/xi2/xz

    - name: Run build
      run: go build .

    - name: Run vet & lint
      run: |
        go vet .
        golint .

    - name: Run testing
      run: cd test && go test -v
