name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.17"
          - "1.18"

    steps:
    - name: Checkout project
      uses: actions/checkout@v3.0.2

    - name: Setup Go (${{ matrix.go }})
      uses: actions/setup-go@v3.2.0
      with:
        go-version: ${{ matrix.go }}

    - name: Install tools and dependencies (${{ matrix.go }})
      run: |
        go version
        go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run build (${{ matrix.go }})
      run: go build -v -a ./...

    - name: Run tests (${{ matrix.go }})
      run: go test -v ./...

    - name: Run vet & staticcheck (${{ matrix.go }})
      run: |
        go vet ./...
        staticcheck ./...
